### PR TITLE
custom png_from_web component

### PR DESCRIPTION
**Pull request by j0ono0**
The Image component in _pinout_ is a bit short sighted and caters purely for local file system paths only.
This pull request includes a custom component that can link or embed a PNG image from a web URL.

I plan to merge this into pinout for later release so a valuable exercise for me to undertake :)

### CODE REVIEW

**Comment by gojimmypi** [comment]
Thank you so much for the PR and the recent changes to [pinout](https://pinout.readthedocs.io/en/latest/), @j0ono0 ! :)

This is certainly curious. the new code change to support the embedded base64 encoded image in the SVG seems to work just fine in the [README.md](./../blob/main/README.md) file (where one would expect the image to be more likely problematic, with the GitHub HTML wrapper)... yet does _not_ work properly in the [raw pinout_ulx3s.svg](https://raw.githubusercontent.com/ulx3s/ulx3s-pinout/main/pinout_ulx3s.svg) link (where it would seem more likely to work, being just a single image file). See the file rendered properly here:

https://github.com/ulx3s/ulx3s-pinout/blob/main/pinout_ulx3s.svg

This image looks fine:

image

but when clicking on "download" button it looks like this:

image

More bizarre: It works properly when Right-click downloading the image from the README.md file, and saving it locally:

image

What do you think, @j0ono0 ?

**Comment by j0ono0** [comment]
Very strange indeed! 

Glad to see it is working on the read me page and downloadable - it's a great use case. 

I'll have a closer look early in the week and post back findings (or bamboozlment!)

**Comment by j0ono0** [comment]
Google Chrome dev tools has shed some light on the mystery: 

_"...because it violates the following Content Security Policy directive: "default-src 'none'". Note that 'img-src' was not explicitly set, so 'default-src' is used as a fallback."_

There appears to be no way to include a 'default-src' in the SVG directly. My feeling is this maybe a limitation of the format and resource delivery via github.

You are definitely breaking new ground with your use of _pinout_ so hard to provide suggestions. With my "UX" hat on I have concerns users may abort the download thinking the resource will be broken. Maybe zipping it with other resources as an 'offline resource pack' would work. Having _pinout_ export as a png would be a nice option and perpetually on my development list. Thwarted so far by complexities of text support.

**Comment by gojimmypi** [comment]
hm. yes, that's not entirely surprising. 

Also, the super-long line of Base64 encoded PNG text was not happy in either Visual Studio nor Chrome/Edge on my pitifully slow machine (both browsers timed out when trying to view the source). I might suggest embedding some linefeeds.

I agree that a PNG `pinout` output would be ideal. I whipped together a quick [svg2png](https://github.com/ulx3s/ulx3s-pinout/tree/main/svg2png) (thanks @svg-net for [SVG converter](https://github.com/svg-net/SVG)), but the [resultant PNG file](https://github.com/ulx3s/ulx3s-pinout/blob/main/pinout_ulx3s.png) is less than optimal:

image

Note the corner rounding and vertical position of text.

**Comment by j0ono0** [comment]
less than optimal but with some promise maybe? .NET and C# are outside my skills so I'll hold-off direct tinkering, but if you are looking for ideas on revision:
- the corners might be an anti-aliasing issue. Seems there is a 'RequiresSmoothRendering' setting: https://svg-net.github.io/SVG/api/Svg.SvgVisualElement.html#Svg_SvgVisualElement_RequiresSmoothRendering
- text offset will be an unsupported CSS rule that vertically aligns the text. If CSS transforms are supported shifting the text that way might be tempting bu slightly hacky. If you are keen to pursue this solution **I'd be happy to write a custom pinlabel class that accepts a text offset value, which would be a robust solution.**

On a side-note: I use InkScape to convert pinout output to png with excellent results. I believe they use cairo graphics library. [cairosvg](https://cairosvg.org/) is in my sights to tryout but has some dependencies that are a little convoluted to install on windows.

**Comment by j0ono0** [comment]
just a quick update - I just installed requirements for cairosvg using this:
https://github.com/tschoonj/GTK-for-Windows-Runtime-Environment-Installer

base64 embedded image failed BUT linked image (from web) worked. Output accuracy looks **_very_** close to browser rendering.

**Pull request merged**
